kind: SwitchConfig
version: v1alpha1
kubeconfigStores:
  - kind: filesystem
    kubeconfigName: "*config"
    required: false
    paths:
      - ~/.kube/
  - kind: filesystem
    kubeconfigName: "*config"
    required: false
    paths:
      - ~/Work/kubeconfig/
  - kind: filesystem
    required: false
    kubeconfigName: "*config*"
    paths:
      - ~/Downloads/
